on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment name'
        type: string
        required: true
      environment_url:
        description: 'Sets the URL for accessing your environment'
        type: string
        required: false
      state:
        description: 'Deployment status'
        type: string
        required: true
      description:
        description: 'A short description of the status'
        type: string
        required: false

jobs:
  set-deployment-status:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github.v3+json" \
          /repos/$OWNER/$REPO/deployments/$DEPLOYMENT_ID/statuses \
          -f environment="$ENVIRONMENT" \
          -f environment_url="$ENVIRONMENT_URL" \
          -f state="$STATE" \
          -f description="$DESCRIPTION"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          DEPLOYMENT_ID: ${{ github.event.deployment.id }}
          ENVIRONMENT: ${{ inputs.environment }}
          ENVIRONMENT_URL: ${{ inputs.environment_url }}
          STATE: ${{ inputs.state }}
          DESCRIPTION: ${{ inputs.description }}
